repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # Run the linter (check only, no auto-fix during commit)
      - id: ruff
        exclude: setup_mongo_acme.py
      # Run the formatter (check only, no auto-fix during commit)
      - id: ruff-format
        args: [ --check ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
